let configurations = [
  { // 1
    radius: 350,
    numberOfPoints: 3,
    factor: 2,
    avoidBackward: -1,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 100,
  },
  { // 2
    radius: 350,
    numberOfPoints: 4,
    factor: 2,
    avoidBackward: 1,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 3
    radius: 350,
    numberOfPoints: 4,
    factor: 2,
    avoidBackward: 2,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 4
    radius: 350,
    numberOfPoints: 4,
    factor: 2,
    avoidBackward: -1,
    avoidForward: -1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 5
    radius: 350,
    numberOfPoints: 4,
    factor: 2.3,
    avoidBackward: -1,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 6
    radius: 350,
    numberOfPoints: 5,
    factor: 2,
    avoidBackward: 1,
    avoidForward: 1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 7
    radius: 350,
    numberOfPoints: 5,
    factor: 2,
    avoidBackward: 2,
    avoidForward: 2,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 8
    radius: 350,
    numberOfPoints: 5,
    factor: 2,
    avoidBackward: 1,
    avoidForward: -1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 9
    radius: 350,
    numberOfPoints: 5,
    factor: 2,
    avoidBackward: 1,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 10
    radius: 350,
    numberOfPoints: 5,
    factor: 2,
    avoidBackward: 2,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 11
    radius: 350,
    numberOfPoints: 5,
    factor: 2,
    avoidBackward: -1,
    avoidForward: -1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 12
    radius: 350,
    numberOfPoints: 5,
    factor: 2.3,
    avoidBackward: -1,
    avoidForward: -1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 13
    radius: 350,
    numberOfPoints: 5,
    factor: 2,
    avoidBackward: -1,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 14
    radius: 350,
    numberOfPoints: 5,
    factor: 2.3,
    avoidBackward: -1,
    avoidForward: -1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 15
    radius: 350,
    numberOfPoints: 6,
    factor: 2,
    avoidBackward: 2,
    avoidForward: 2,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 16
    radius: 350,
    numberOfPoints: 6,
    factor: 2,
    avoidBackward: 1,
    avoidForward: 3,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 17
    radius: 350,
    numberOfPoints: 7,
    factor: 2.5,
    avoidBackward: -1,
    avoidForward: 1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 18
    radius: 350,
    numberOfPoints: 7,
    factor: 2.5,
    avoidBackward: -1,
    avoidForward: 2,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 19
    radius: 350,
    numberOfPoints: 7,
    factor: 2.5,
    avoidBackward: 3,
    avoidForward: 3,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 20
    radius: 350,
    numberOfPoints: 7,
    factor: 2.5,
    avoidBackward: -1,
    avoidForward: 3,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 21
    radius: 350,
    numberOfPoints: 7,
    factor: 2.5,
    avoidBackward: 5,
    avoidForward: 5,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 22
    radius: 350,
    numberOfPoints: 7,
    factor: 2.5,
    avoidBackward: -1,
    avoidForward: 5,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 23
    radius: 350,
    numberOfPoints: 8,
    factor: 2,
    avoidBackward: 1,
    avoidForward: 1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 24
    radius: 350,
    numberOfPoints: 8,
    factor: 2,
    avoidBackward: 1,
    avoidForward: 1,
    avoidLast: -1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 25
    radius: 350,
    numberOfPoints: 8,
    factor: 2,
    avoidBackward: 2,
    avoidForward: 2,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 26
    radius: 350,
    numberOfPoints: 8,
    factor: 2,
    avoidBackward: 3,
    avoidForward: 3,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 27
    radius: 350,
    numberOfPoints: 8,
    factor: 2,
    avoidBackward: 1,
    avoidForward: 5,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 28
    radius: 350,
    numberOfPoints: 8,
    factor: 2,
    avoidBackward: 2,
    avoidForward: 5,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 29
    radius: 350,
    numberOfPoints: 8,
    factor: 2,
    avoidBackward: 5,
    avoidForward: 5,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 30
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 1,
    avoidForward: 1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 31
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 9,
    avoidForward: 1,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 32
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 2,
    avoidForward: 2,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 33
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 3,
    avoidForward: 3,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 34
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 4,
    avoidForward: 4,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 35
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 5,
    avoidForward: 5,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 36
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 1,
    avoidForward: 6,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 37
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 6,
    avoidForward: 6,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 38
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 7,
    avoidForward: 7,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 39
    radius: 350,
    numberOfPoints: 10,
    factor: 2.1,
    avoidBackward: 8,
    avoidForward: 8,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 40
    radius: 350,
    numberOfPoints: 10,
    factor: 2.3,
    avoidBackward: 8,
    avoidForward: 8,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 41
    radius: 350,
    numberOfPoints: 10,
    factor: 2.5,
    avoidBackward: 8,
    avoidForward: 8,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  },
  { // 42
    radius: 350,
    numberOfPoints: 15,
    factor: 3.8,
    avoidBackward: 5,
    avoidForward: 5,
    avoidLast: 1,
    centralizeX: 0,
    centralizeY: 0,
  }
]
